name: brew test-bot
on:
  push:
    branches:
      - main
  pull_request:
env:
  HOMEBREW_CHANGE_ARCH_TO_ARM: 1
jobs:
  test-bot:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest-large, macos-latest-xlarge]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Homebrew Bundler RubyGems
        run: brew install-bundler-gems


      # Remove anything that looks like a toolchain formula. Detecting this
      # by looking for formulas with three dashes is gross, but works.
      - run: brew ls --formula | grep -- '-.*-.*-.*' | xargs brew uninstall -f

      - run: brew uninstall -f openssl@1.1

      - name: Make sure homebrew-core is clean
        run: git clean -f -d
        working-directory: /usr/local/Homebrew/Library/Formula/o

      - run: brew cleanup

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax

      # https://github.com/crosstool-ng/crosstool-ng/issues/1477#issuecomment-998361621
      - run: brew install --HEAD crosstool-ng

      - run: brew test-bot --only-formulae
        if: github.event_name == 'pull_request'

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@main
        with:
          name: bottles
          path: '*.bottle.*'
